name: CI Pipeline

on:
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Backend tests
        run: mvn -f authorization-server test

      - name: Frontend tests
        run: |
          cd ag-prueba-front
          npm install
          npm test -- --watch=false
