name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------
      # BACKEND: Authorization Server
      # -------------------------
      - name: Build & Test Authorization Server
        run: |
          cd authorization-server
          mvn clean test

      # -------------------------
      # BACKEND: Resource Server
      # -------------------------
      - name: Build & Test Resource Server
        run: |
          cd resource-server
          mvn clean test

      # -------------------------
      # FRONTEND: Angular
      # -------------------------
      - name: Install dependencies for Angular
        run: |
          cd ag-prueba-front
          npm install

      - name: Angular Unit Tests
        run: |
          cd ag-prueba-front
          npm test -- --watch=false --browsers=ChromeHeadless
