name: CI Pipeline

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------
      # BACKEND: Authorization Server
      # -------------------------
      - name: Build Authorization Server
        run: |
          cd authorization-server
          mvn -q -DskipTests clean package

      # -------------------------
      # BACKEND: Resource Server
      # -------------------------
      - name: Build Resource Server
        run: |
          cd resource-server
          mvn -q -DskipTests clean package

      # -------------------------
      # FRONTEND: Angular
      # -------------------------
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies for Angular
        run: |
          cd ag-prueba-front
          npm install

      - name: Angular Build
        run: |
          cd ag-prueba-front
          npm run build --if-present
