name: Deploy Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Start Timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      # -----------------------------------------
      # BACKEND 1: Authorization Server
      # -----------------------------------------
      - name: Build Authorization Server
        run: |
          cd authorization-server
          mvn clean package -DskipTests

      # -----------------------------------------
      # BACKEND 2: Resource Server
      # -----------------------------------------
      - name: Build Resource Server
        run: |
          cd resource-server
          mvn clean package -DskipTests

      # -----------------------------------------
      # FRONTEND Angular
      # -----------------------------------------
      - name: Build Angular Frontend
        run: |
          cd ag-prueba-front
          npm install
          npm run build

      - name: End Timer
        run: echo "END_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Deployment Duration
        run: echo "Tiempo de despliegue: $((END_TIME-START_TIME)) segundos" >> $GITHUB_STEP_SUMMARY
