name: Deploy Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start Timer
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      # -----------------------------------------
      # BACKEND 1: Authorization Server (simulado)
      # -----------------------------------------
      - name: Build Authorization Server
        run: echo "Build Authorization Server simulado"

      # -----------------------------------------
      # BACKEND 2: Resource Server (simulado)
      # -----------------------------------------
      - name: Build Resource Server
        run: echo "Build Resource Server simulado"

      # -----------------------------------------
      # FRONTEND Angular (simulado)
      # -----------------------------------------
      - name: Build Angular Frontend (simulado)
        run: |
          if [ -f "./ag-prueba-front/package.json" ]; then
            echo "Build Angular simulado"
          else
            echo "No frontend. Skip step"
          fi

